---
sudo: required
language: python

services:
  - docker

env:
  - MOLECULE_OS=centos:7
  - MOLECULE_OS=ubuntu:xenial
  - MOLECULE_OS=ubuntu:bionic
  - MOLECULE_OS=ubuntu:trusty

install:
  - pip install molecule docker

script:
  - molecule test
