---
sudo: required
language: python

services:
  - docker

env:
  - MOLECULE_OS=centos:latest
  - MOLECULE_OS=ubuntu:latest
  - MOLECULE_OS=debian:latest
  - MOLECULE_OS=fedora:latest

install:
  - pip install molecule docker

script:
  - molecule test
