---
# tasks files for docker related tasks

- name: Add CentOS docker-ce repo.
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add Ubuntu docker-ce repo.
  apt_repository:
    repo: |-
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  when: 
    - ansible_distribution == 'Debian' 
    - ansible_distribution == 'Ubuntu'
  register: docker

- name: Add Ubuntu docker-ce gpg key.
  shell: |-
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: false
  when: 
    - ansible_distribution == 'Debian' 
    - ansible_distribution == 'Ubuntu'

- name: Run apt-get update.
  shell: apt-get update
  args:
    warn: false
  when: 
    - ansible_distribution == 'Debian' 
    - ansible_distribution == 'Ubuntu'

- name: Install docker-ce on host.
  package:
    name: docker-ce

- name: Add user to docker usergroup.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable docker to start on boot.
  service: name=docker enabled=true

- name: Start docker service.
  service: name=docker state=started
  when: ansible_connection != "docker"
