---
# tasks files for docker related tasks

- name: Add CentOS docker-ce repo.
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true
  when: >
    ansible_distribution == 'CentOS'
    or
    ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add CentOS docker-ce repo.
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repo
    baseurl: >
      https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: true
  when: ansible_distribution == 'Fedora'

- name: Enable Fedora docker-ce repo.
  command: dnf config-manager --set-enabled docker-ce-stable
  when: ansible_distribution == 'Fedora'

- name: Add Ubuntu docker-ce repo.
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/ubuntu
      "{{ ansible_lsb.codename }}"
      stable
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add Ubuntu docker-ce gpg key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install docker-ce on CentOS host.
  yum:
    name: docker-ce
  when: >
    ansible_distribution == 'CentOS'
    or
    ansible_distribution == 'Red Hat Enterprise Linux'
    or
    ansible_distribution == 'Fedora'

- name: Install docker-ce on Ubuntu host.
  apt:
    name: docker-ce
    update_cache: true
    allow_unauthenticated: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add user to docker usergroup.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable docker to start on boot.
  service: name=docker enabled=true

- name: Start docker service.
  service: name=docker state=started
  when: ansible_connection != "docker"
